baseURL = "https://rijnieks.com/"
languageCode = "en-us"
title = "Krisjanis Rijnieks"

[params]
  subtitle = "Creative Coding. Projection Mapping. Solutions"
  author = "Krisjanis Rijnieks"
  description = "The online presence of creative technologist and artist Krisjanis Rijnieks"
  keywords = ["creative coding", "projection mapping", "raspberry pi", "video mapping", "programming", "installations", "multimedia", "interaction", "design", "electronics", "prototyping", "fab lab", "maker", "artist", "designer", "developer"]
  social = [
    {title="Krisjanis Rijnieks on GitHub", url="https://github.com/kr15h", icon="fa-github"}, 
    {title="Krisjanis Rijnieks on Instagram", url="https://www.instagram.com/kriwkrow", icon="fa-instagram"},
    {title="Krisjanis Rijnieks on Twitter", url="https://twitter.com/kriwkrow", icon="fa-twitter"},
    {title="Krisjanis Rijnieks on LinkedIn", url="http://www.linkedin.com/in/krisjanisrijnieks", icon="fa-linkedin"}
  ]
